vich_uploader:
   db_driver: orm

   mappings:
      entries_image:
         uri_prefix: "%app.path.entries_image%"
         upload_destination: "%kernel.project_dir%/public%app.path.entries_image%"
         namer: Vich\UploaderBundle\Naming\OrignameNamer
